tasks
Homegor/JFD pull request #10
Opened 2023-04-30 05:07 UTC by Homegor

2023-05-01 14:32 UTC, Solexofficial commented on React/fast-company/src/App.js
>      const [users, setUsers] = useState(api.users.fetchAll())
изначально пустой массив, либо null

2023-05-10 09:24 UTC, Solexofficial requested changes

2023-05-10 09:24 UTC, Solexofficial commented on React/fast-company/src/App.js
> +    const filteredUsers = selectedProf ? users.filter(user => user.profession.name === selectedProf.name) : users
верно поправил, но безопаснее будет сравнивать по id

2023-05-10 09:24 UTC, Solexofficial commented on React/fast-company/src/components/groupList.jsx
> +    const itemsArr = Array.isArray(items) ? items : Object.values(items)
тут отлично, но почему в итоге не используешь itemsArr?

2023-05-10 09:49 UTC, Homegor commented on React/fast-company/src/components/groupList.jsx
> +    const itemsArr = Array.isArray(items) ? items : Object.values(items)
Да, я немного уже подправил, + убрал логирование

2023-05-10 09:50 UTC, Homegor commented on React/fast-company/src/App.js
> +    const filteredUsers = selectedProf ? users.filter(user => user.profession.name === selectedProf.name) : users
Тут тоже уже попровил

2023-05-10 17:53 UTC, merged