hw-1
Homegor/JFD pull request #20
Opened 2023-03-15 06:38 UTC by Homegor

2023-03-15 17:23 UTC, Solexofficial commented on module_1/Week_7/01_asinc-await/lesson_2/index.js
> +    const requests = await ids.map((id) => fetch(`${TODOS_URL}/${id}`));
здесь await ничего ждать не будет) ты мапишь массив в массив промисов, чтобы ожидать выполнение каждого нужен цикл for of

2023-03-15 17:25 UTC, Homegor commented on module_1/Week_7/01_asinc-await/lesson_2/index.js
> +    const requests = await ids.map((id) => fetch(`${TODOS_URL}/${id}`));
Так я же его удалил. Надо перепроверить. Я понял о чем ты говорил. Мне даже ide подчеркивала код

2023-03-15 17:25 UTC, Solexofficial commented on module_1/Week_7/02_callback-Event Loop/lesson_1/index.js
> +    console.log('Promise'); // войдет в микрозадачу
все что в создании промиса, синхронный код
console.log(Promise) первым попадает в callstack

2023-03-15 17:26 UTC, Solexofficial commented on module_1/Week_7/02_callback-Event Loop/lesson_1/index.js
> +    console.log('Promise resolve'); // войдет в микрозадачу
тут верно)

2023-03-15 17:37 UTC, Homegor commented on module_1/Week_7/02_callback-Event Loop/lesson_3/index.js
> +*   1) Success (четвертая)
Мне переделывать или как? Или самому теперь вызвать все в консоль и проверить?

2023-03-15 17:38 UTC, Homegor commented on module_1/Week_7/02_callback-Event Loop/lesson_1/index.js
> +    console.log('setTimeout'); // войдет в вызов
Кстати да, странно что я ее в вызов записал

2023-03-15 17:40 UTC, Solexofficial requested changes
3-ую задачу нужно еще раз обдумать.

Подсказки на запомнить:
Как работает ивент луп:
Выполняет сначала всё, что лежит в execution callstack(сюда попадают вызовы функции, тот же самый консоль.лог - это вызов функции, при создании промиса весь код внутри синхронный, поэтом если там есть console.log он сразу попадает в callstack)
Далее смотрит в очередь микрозадач(если брать базовые вещи, то туда попадает все, что происходит после резолва промиса, then )
Далее смотрит в очередь макрозадач и берет оттуда одну(туда попадают setTimeout, setInterval, addEventListener колбэки и другое, что предоставляет нам среда, в конкретном случае это webAPI браузера)

Далее смотрит, если очередь микрозадач пустая, то продолжает вытягивать задачи из очереди макрозадач.

2023-03-15 17:41 UTC, Solexofficial commented on module_1/Week_7/02_callback-Event Loop/lesson_3/index.js
> +*   1) Success (четвертая)
Можешь вызывать в консоль, главное чтобы ты понимал, почему именно такой порядок

2023-03-15 17:41 UTC, Solexofficial commented on module_1/Week_7/02_callback-Event Loop/lesson_3/index.js
> +*   1) Success (четвертая)
И да, нужно снова написать верный порядок и объяснить почему именно так

2023-03-17 13:45 UTC, Solexofficial commented on module_1/Week_7/02_callback-Event Loop/lesson_1/index.js
> +    console.log('setTimeout'); // микрозадачи выполнится в последнюю очередь
макро*

2023-03-17 13:53 UTC, Solexofficial approved these changes

2023-03-17 19:31 UTC, merged