вот и проверим
Homegor/JFD pull request #25
Opened 2023-03-28 21:36 UTC by Homegor

Дополнительное задание по функциям

2023-03-29 19:20 UTC, Solexofficial commented on module_1/Week_2/03_Additionally/lesson_1/index.js
> +    //const answer = prompt('')
давай почистим код и уберем лишние комментарии.
а где сейчас мы получаем ввод пользователя?

2023-03-29 19:21 UTC, Solexofficial commented on module_1/Week_2/03_Additionally/lesson_2/index.js
> +    let notError = 0
да, тут действительно нужен флаг для определения ошибки.
но вернее будет назвать isError и значение у нас может быть либо есть ошибка, либо её нет. зачем нам числа, когда у нас есть прекрасный тип boolean

2023-03-29 19:22 UTC, Solexofficial commented on module_1/Week_2/03_Additionally/lesson_2/index.js
> +        const indexError = text[i]
здесь на каждой итерации создается новая переменная, достаточно. +  в текущем случае indexError - это currentSymbol

2023-03-29 19:23 UTC, Solexofficial requested changes
need fix

2023-03-30 02:34 UTC, Homegor commented on module_1/Week_2/03_Additionally/lesson_1/index.js
> +    //const answer = prompt('')
По логике сначала пользователь видит вопрос, потом вводит ответ, а после идет логика.

2023-03-30 02:34 UTC, Homegor commented on module_1/Week_2/03_Additionally/lesson_2/index.js
> +    let notError = 0
В этом есть логика, забываю порой про boolean

2023-03-30 02:36 UTC, Homegor commented on module_1/Week_2/03_Additionally/lesson_2/index.js
> +    let notError = 0
Наверно мне будет не лишним если ты меня погоняешь по названиям функций и переменных, так как не первый раз говоришь про адекватные названия и  то что я сам путаюсь в дальнейшем

2023-03-30 06:04 UTC, Homegor commented
Поправил.

2023-03-30 22:28 UTC, Solexofficial approved these changes

2023-03-30 22:52 UTC, merged